name = "bohraz/arch"
version = "0.1.0"
authors = ["bohraz"]
repository = "https://github.com/bohraz/Arch"
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
jecs = { wally = "ukendio/jecs", version = "^0.5.3" }
sift = { wally = "csqrl/sift", version = "^0.0.9" }
signal = { wally = "sleitnick/signal", version = "^2.0.3" }
janitor = { wally = "howmanysmall/janitor", version = "^1.17.0" }
testez = { wally = "roblox/testez", version = "^0.4.1" }
